### ISSUE TITLE
Decent CI is broken                                                    - OK well maybe not.

### ISSUE THREAD

**Issue by Myoldmopar** [lefticus/decent_ci#5]
So, the failing tests on NREL/OpenStudio like [these](https://nrel.github.io/OpenStudioBuildResults/OpenStudio-8ec7bef3a79dbd3b43075b5b7dbeff00d04976b6-x86_64-MacOS-10.9-clang.html) seem to lean toward a PATH or Ruby Path or something problem, right?  Could it be that the PATH is being pruned down and something needs to be re-added to ENV?  Just throwing out ideas that might be quick fixes to get NREL/OpenStudio CI results meaningful.  kthxbye lolcatz

**Comment by lefticus** [comment]
Actually considering the remaining 2100 tests are listed as "not run" I'm thinking that actually means the entire build failed.

**Comment by lefticus** [comment]
@Myoldmopar  FYI, I'm looking into this. All CI builds of openstudio are broken on all platforms right now.

**Comment by lefticus** [comment]
I'm closing this as the actual issue was too deep down in cmake logging for me to report it effectively
